### ISSUE TITLE
Media queries in _after

### ISSUE THREAD

**Issue by TomasNyvlt** [xcorejs/ui#33]
There is a bug in _after props, when I can't use media queries as object, but need to write it in Array:

<img width="501" alt="Snímek obrazovky 2020-02-13 v 15 20 17" src="https://user-images.githubusercontent.com/6454135/74443997-77b8e400-4e74-11ea-88f0-395381ae58a2.png">

**Comment by pavelvondrasek** [comment]
@AlfonzAlfonz I think it's caused by we use `@styled-system/css` which is theme-aware.

It's why arrays work.

We have to add object to array converter.
